---
- name: Install ZNC from repositories
  package: name=znc state=present
  when: (znc_from_repo = "always") or (znc_version |version_compare(znc_from_repo, "<="))

- include: install_from_src.yml
  when: (znc_from_repo != "always") and (znc_version |version_compare(znc_from_repo, ">")
