---
- name: Download ZNC source tarball
  get_url: url=http://znc.in/releases/archive/znc-{{ znc_version }}.tar.gz dest=.

- name: Extract ZNC source tarball
  unarchive: src=znc-{{ znc_version }}.tar.gz copy=no dest=.
  
- name: Configure ZNC compilation
  command: ./configure
  args:
    chdir: znc-{{ znc_version }}
    creates: znc-{{ znc_version }}/Makefile

- name: Compile ZNC
  command: make
  args:
    chdir: znc-{{ znc_version }}

- name: Install ZNC
  command: make install
  args:
    chdir: znc-{{ znc_version }}
  become: true
