---
- name: Find the installed version of ZNC
  shell: '/usr/local/bin/znc --version | grep -Poh "^ZNC \K([0-9.]+)"'
  ignore_errors: yes
  register: znc_installed_version

- include: install.yml
  when: (znc_installed_version.rc != 0) or (znc_version | version_compare(znc_installed_version.stdout, "!="))

- name: Create znc user
  user: name=znc comment="Account to run ZNC daemon" home="/var/lib/znc"  system=yes state=present

- name: Generate password salt
  set_fact:
    znc_salt: "{{ 20 |znc_random }}"

- name: Upload ZNC config
  template: src=znc.conf dest=/var/lib/znc/configs/znc.conf
  become_user: znc
  become: true

- name: Upload ZNC initscript
  copy: src=znc.init dest=/etc/init.d/znc
  when: ansible_service_mgr != "systemd"

- name: Enable and start ZNC
  service: name=znc state=started enabled=yes
