---
- name: Install nginx
  apt: name=nginx state=latest default_release=jessie-backports
#  pacman: name=nginx state=present

- name: Upload nginx config
  copy: src={{ item }} dest=/etc/nginx/ backup=yes
  with_fileglob:
    - "*.conf"
  notify: reload nginx

# FIXME: make this indempotent
- name: Clear previous managed vhosts
  file: path=/etc/nginx/ans-sites-enabled state=absent
  notify: reload nginx

- name: Make managed vhost directory
  file: path=/etc/nginx/{{item}} state=directory
  with_items:
    - ans-sites-enabled
    - ans-sites-available
    - ans-fragments
  notify: reload nginx

- name: Create the acme group
  group: name=acme system=yes state=present

- name: Create the acme-challenge parent directory
  file: path=/srv/acme/.well-known state=directory

- name: Create the acme-challenge directory
  file: path=/srv/acme/.well-known/acme-challenge state=directory group=acme mode=775

- name: Enable and start nginx
  service: name=nginx state=started enabled=yes
