- name: "Upload landing page nginx config"
  template: src=landing.conf dest=/etc/nginx/ans-fragments/wolf-landing
- name: "Register as part of {{vhost}}"
  # A giant hack
  set_fact:
    nginx_fragments: '{{ {vhost: nginx_fragments[vhost] |default([]) |union(["wolf-landing"]) } }}'
